version: '3'
services:
  db:
    image: mysql
    build: ./seed
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
       - "3316:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: minadadmin 
    volumes:
      - ./databases/mysql:/var/lib/mysql
  redis:
    build: ./redis
    image: redis
    restart: always
    ports:
       - "6379:6379"
  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - "27117:27017"
    volumes:
      - ./databases/mongo:/data/db
      - ./databases/dump:/dump
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec thin start  --port 3000 --ssl  --ssl-key-file config/ssl/private.key --ssl-cert-file config/ssl/server.crt"
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec  puma -t 8:32 -w 4 -b 'ssl://0.0.0.0:3000?key=ssl/ssl.key&cert=ssl/ssl.cert&verify_mode=none' -e production"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec thin start  --port 3000 --ssl -e production"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec thin start  --port 3000 --ssl"
    volumes:
      - .:/docker_app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
      - mongo
      - redis
