apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: your-web-app-image:latest
          command: ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec thin start --port 3000 --ssl --ssl-key-file config/ssl/private.key --ssl-cert-file config/ssl/server.crt"]
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://root:minadadmin@mysql:3306/mydb"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30080
  selector:
    app: web-app